### ISSUE TITLE
Crashes latest Zotero version

### ISSUE THREAD

**Issue by champagnealexandre** [windingwind/zotero-tag#36]
Hi,

Just installed the plugin and tried automatically tagging items ; every time I’m adding a new item Zotero crashes.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/30211986/191138560-ecb62a90-92c5-48c2-a28a-9846c54df991.png">

Zotero version: 6.0.13
Plugin version: 0.2.17

<img width="615" alt="image" src="https://user-images.githubusercontent.com/30211986/191138631-903fa3e7-ff5c-4683-a948-e43322b2edfc.png">

**Comment by windingwind** [comment]
Sorry to know that. Hope it does not cause any data loss.
It’s so weird that in the last 2 years since I first made this plugin, no similar issues are reported. This plugins has been widely used by more than 10k people.
Could you please check:
1. re-install the plugin;
2. select an item in the library view;
3. press `alt+1` to trigger the plugin to add a tag to the selected item, which works in the same way as the item add action;
4. or, right-click on an item and click ‘add/remove tags’ to manually add some tags to them.

Does any step cause a crash, or the crash only happens when you add new items?

5. set all rules’ action to ‘disabled’ and add a new item to your library

Does this step cause a crash?

And, I need to know if there are any other plugins you are using. If any of them also does something when new items are added, please try to disable them and try this plugin again(with some item add rules).

Please let me know if this happens all the time or it is resolved. Thanks!

**Comment by champagnealexandre** [comment]
Hi @windingwind,

Thanks for taking the time to reply. No, there was no data loss thankfully!

Step 1 had no effect, steps 2-3-4 resulted in tags being added, and step 5 resulted in no crash.

I have then proceeded to disable all by one the ~10 plugins I’m using and turns out that when _both_ zotero-tag and [zotero-citationcounts](https://github.com/eschnett/zotero-citationcounts/) are enabled, adding new items crashes Zotero. I have tried updating zotero-citationcounts to the latest version (1.3.0) and the crashes still occur.

In the meantime I have disabled zotero-citationcounts but let me know if you find a solution to this!

Thanks for your time, and for developing this plugin!

**Comment by champagnealexandre** [comment]
I’ve created a post in the Zotero forums about this issue: https://forums.zotero.org/discussion/99865/plugins-causing-segmentation-fault-when-used-together-citation-counts-manager-zotero-tag?new=1

**Comment by windingwind** [comment]
Hi, is this solved? Should I keep this thread open?

**Comment by champagnealexandre** [comment]
This is not solved but when I disable zotero-citationcounts the crashes do not occur. So I think this has to be solved by @eschnett. Thanks!

**Comment by sbaross** [comment]
Hi, I'm also getting the same issue when using zotero-tag in combination with DOI manager (https://github.com/bwiernik/zotero-shortdoi), I would appreciate if this could be looked into further.

I'm using zotero tag v0.3.0 with zotero v6.0.21 on macOS monterey, happy to help troubleshoot or give more info if needed!
